
export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECTS = 'ADD_PROJECTS';
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';